In [1]:
import openpyxl
import pandas as pd
import re
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer
from sklearn.decomposition import NMF
from sklearn.preprocessing import normalize
from gensim import corpora, models

C:\Users\gwons\anaconda3\envs\pykernel3.7.3\lib\site-packages\gensim\similarities\__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)

In [2]:
#날짜별 수집을 위한 Dates 리스트 준비(2000.01~2021.10)
read_file="C:\\Users\\User\\Desktop\\뉴스데이터 수집\\RawData\\Date_Filter\\Date.xlsx"

before=pd.read_excel(read_file,usecols=[0])
Before=before.values.tolist()
Before=sum(Before,[]) #날짜 데이터 준비
Before=list(map(str,Before))

after=pd.read_excel(read_file,usecols=[1])
After=after.values.tolist()
After=sum(After,[]) #날짜 데이터 준비
After=list(map(str,After))

In [3]:
def get_topics(models,num):
    #the word ids obtained need to be reverse-mapped to the words so we can print the topic names.
    feat_names = vectorizer.get_feature_names()
    
    word_dict = {};
    for i in range(num):
        
        #for each topic, obtain the largest values, and add the words they map to into the dictionary.
        words_ids = model.components_[i].argsort()[:-10 - 1:-1]
        words = [feat_names[key] for key in words_ids]
        word_dict['Topic # ' + '{:02d}'.format(i+1)] = words;
    
    return pd.DataFrame(word_dict);

In [5]:
#데이터셋 준비
document=[]

for i in range(17,262):
    read_file="C:\\Users\\User\\Desktop\\뉴스데이터 수집\\RawData\\Filtered\\NewsResult_Filtered\\NewsResult_"+Before[i]+"-"+After[i]+".xlsx"
    
    data=pd.read_excel(read_file,usecols=[2])
    tmp_document=data.values.tolist()
    tmp_document=sum(tmp_document,[])

    document=document+tmp_document
    
print("Document Ready")

Document Ready

In [15]:
docs=pd.DataFrame(document)
docs.to_excel('total news.xlsx')

In [6]:
text=document
vectorizer=CountVectorizer(analyzer='word')
x_counts=vectorizer.fit_transform(text)

transformer=TfidfTransformer(smooth_idf=False)
x_tfidf=transformer.fit_transform(x_counts)

In [8]:
xtfidf_norm=normalize(x_tfidf,norm='l2',axis=1)

print("xtfidf_norm Ready")
#obtain a nmf model
model=NMF(n_components=80,init='nndsvd')
model.fit(xtfidf_norm)

print("Model Ready")

xtfidf_norm Ready
Model Ready

In [9]:
print('tf-idf Dimensions '+str(x_tfidf.shape))
print('Feature Dimensions '+str(xtfidf_norm.shape))
print('Components Dimensions '+str(model.components_.shape))

tf-idf Dimensions (42054, 214468)
Feature Dimensions (42054, 214468)
Components Dimensions (80, 214468)

In [10]:
# Create a DataFrame: components_df
components_df = pd.DataFrame(model.components_, columns=vectorizer.get_feature_names())

,aa,aaa,aacc,aachen,aada,aaig,aastm,aat,aau,aawa,...,林鍾烈,臨事而懼,臨南,臨檢,臨港新城,臨渴掘井,立國,立春,立案,立法
0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,...,0.0,0.000000,0.0,0.000000,0.000091,0.000000,0.000000,0.000000,0.000000e+00,0.0
1,0.000000,0.000000,0.0,0.0,0.003387,0.0,0.000000,0.000000,0.0,0.000000,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.0
2,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.0
3,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.0
4,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,...,0.0,0.000000,0.0,0.000000,0.000000,0.000302,0.000000,0.000000,7.359787e-05,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.0
76,0.045046,0.004243,0.0,0.0,0.000000,0.0,0.000000,0.000412,0.0,0.000000,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000324,0.000000e+00,0.0
77,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000227,0.0,0.000772,...,0.0,0.000114,0.0,0.000000,0.000017,0.000000,0.000000,0.000000,0.000000e+00,0.0
78,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,...,0.0,0.000000,0.0,0.000000,0.000000,0.000160,0.000000,0.000000,0.000000e+00,0.0
79,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.002742,0.000000,0.0,0.000033,...,0.0,0.000000,0.0,0.000909,0.000000,0.000000,0.000371,0.000000,8.264427e-07,0.0

In [11]:
for topic in range(components_df.shape[0]):
    tmp = components_df.iloc[topic]
    
    print(f'For topic {topic+1} the words with the highest value are:')
    
    print(tmp.nlargest(25))
    print(type(tmp.nlargest(10)))
    print('\n')

For topic 1 the words with the highest value are:
정부     15.544224
대책      2.847325
방안      2.181947
정책      1.323824
지적      1.270121
사태      1.249368
경쟁력     1.195239
업계      1.146036
부처      1.035265
마련      1.027844
책임      1.010384
비판      0.889225
합병      0.854499
검토      0.824505
상황      0.794765
해운업     0.789850
지원      0.740501
요구      0.724812
투입      0.685435
위기      0.672413
추진      0.670284
해결      0.654377
조선업     0.649198
강화      0.596642
주장      0.573860
Name: 0, dtype: float64
<class 'pandas.core.series.Series'>


For topic 2 the words with the highest value are:
운임             8.142709
컨테이너           2.177718
scfi           1.548224
상승             1.452556
물동량            0.978753
지수             0.977024
전주             0.973354
항로             0.954706
최고             0.844230
해상             0.830389
기록             0.770881
성수기            0.728418
상승세            0.724702
유럽             0.712990
급등             0.608415
상하이컨테이너운임지수    0.601595
사상             0.564360
대비             0.529338
화물             0.508727
feu            0.505384
미주             0.502350
컨테이너선          0.490740
운송             0.488422
수준             0.472067
경신             0.460359
Name: 1, dtype: float64
<class 'pandas.core.series.Series'>


For topic 3 the words with the highest value are:
한진해운    5.955078
법정관리    0.727917
법원      0.568222
파산      0.490252
법정      0.446939
청산      0.392567
회생      0.383766
자산      0.301499
사태      0.292446
신청      0.288924
관리      0.284362
절차      0.249775
압류      0.241864
터미널     0.237751
결정      0.228953
피해      0.224603
한진      0.221932
하역      0.207650
물류대란    0.203747
최은영     0.187900
직원      0.180604
해외      0.156024
선고      0.153307
억류      0.149263
해운업     0.140013
Name: 2, dtype: float64
<class 'pandas.core.series.Series'>


For topic 4 the words with the highest value are:
조정      8.787457
구조      8.624640
구조조정    6.136783
조선      1.438458
추진      1.109378
산업      0.932497
조선업     0.918178
위원장     0.878518
해운업     0.786254
진행      0.734766
인력      0.680679
협의체     0.639828
부실기업    0.635797
업종      0.623758
철강      0.618339
방향      0.594083
임종룡     0.567797
금융위     0.562451
금융      0.521370
감축      0.508003
주도      0.501541
정리      0.501462
부실      0.472206
원칙      0.465564
합병      0.424896
Name: 3, dtype: float64
<class 'pandas.core.series.Series'>


For topic 5 the words with the highest value are:
회장         19.443348
최은영         2.166865
경영          1.920038
조양호         1.450378
조수호         1.226067
현정          0.991648
주식          0.858083
유수홀딩스       0.814798
여성          0.754377
회사          0.695272
남편          0.678451
출연          0.665675
사재          0.651964
경영권         0.637737
생각          0.614699
취임          0.593046
명예          0.574228
인물          0.539237
별세          0.538338
위기          0.537533
한진해운홀딩스     0.537375
영향력         0.532423
오너          0.510573
일가          0.494695
이진방         0.491688
Name: 4, dtype: float64
<class 'pandas.core.series.Series'>


For topic 6 the words with the highest value are:
그룹       12.836404
계열사       5.198111
sm상선      2.323179
우방        2.236029
sm        2.077110
중공업       1.657654
회사        1.621996
법인        1.349323
재계        1.246768
sm그룹      1.218644
사업        1.087232
상선        1.062555
sk        1.049139
임병석       0.753863
우오현       0.744949
상장        0.733133
stx그룹     0.724079
주력        0.709004
자산        0.702801
진도        0.686577
성장        0.660304
건설        0.643827
삼성        0.599546
설립        0.590078
해운        0.587672
Name: 5, dtype: float64
<class 'pandas.core.series.Series'>


For topic 7 the words with the highest value are:
현대상선      8.368593
유창근       0.449909
가입        0.246394
산업은행      0.241768
관계자       0.241251
유조선       0.239096
경쟁력       0.204645
적자        0.203259
해운업       0.197671
합병        0.161340
주주        0.148549
글로벌       0.146298
경영        0.145530
내정자       0.139059
영업        0.134719
연지동       0.127982
부채비율      0.122229
영업력       0.121330
한국선박해양    0.118200
터미널       0.113217
확보        0.112788
계약        0.111780
출자전환      0.110253
vlcc      0.106354
현대증권      0.103490
Name: 6, dtype: float64
<class 'pandas.core.series.Series'>


For topic 8 the words with the highest value are:
수주        6.143715
현대중공업     2.126399
발주        2.094005
조선        2.029934
조선업       1.803386
삼성중공업     1.724174
조선사       1.646256
cgt       1.210745
달러        1.014293
조선소       0.929396
조선업계      0.809016
건조        0.783158
대우조선해양    0.700581
플랜트       0.677199
유조선       0.650696
발주량       0.623596
일감        0.585785
수주량       0.574511
계약        0.551163
업체        0.524550
물량        0.520311
잔량        0.520240
취소        0.501854
조선사들      0.442136
컨테이너선     0.437643
Name: 7, dtype: float64
<class 'pandas.core.series.Series'>


For topic 9 the words with the highest value are:
선박      26.326304
건조       2.881492
운항       2.456609
발주       2.184210
관리       1.060320
확보       1.046970
조선소      0.980050
투입       0.973924
스마트십     0.925399
검사       0.883266
하역       0.850163
매입       0.810974
벌크선      0.790943
선박금융     0.764408
선주       0.760740
선령       0.757109
용선       0.753590
해체       0.751344
신조       0.722899
해운업계     0.719507
보유       0.714535
연료       0.695034
입항       0.690007
dwt      0.689805
등록       0.683607
Name: 8, dtype: float64
<class 'pandas.core.series.Series'>


For topic 10 the words with the highest value are:
hmm       5.845542
투입        0.381753
알헤시라스호    0.376981
최대        0.374903
만선        0.365569
재건        0.360625
배재훈       0.340566
출항        0.236060
명명식       0.194929
전환        0.190195
알헤시라스     0.174600
선복량       0.169545
유럽        0.167765
기록        0.147170
산은        0.141425
선적량       0.139358
초대형       0.139293
cb        0.137287
파산        0.136208
경신        0.134310
디얼라이언스    0.129153
scfi      0.128837
해운재건      0.125082
임시        0.120854
대한민국      0.120402
Name: 9, dtype: float64
<class 'pandas.core.series.Series'>


For topic 11 the words with the highest value are:
수사       3.342013
검찰       2.959359
비리       1.542269
혐의       1.172888
검사       0.769070
압수수색     0.763962
부산지검     0.625612
구속       0.604594
의혹       0.602565
일가       0.600915
조사       0.576222
압수       0.574365
인천지검     0.529419
유병언      0.522032
수색       0.515726
소환       0.476945
특별       0.436569
기소       0.404404
청해진해운    0.386904
로비       0.354575
사건       0.345403
특별수사팀    0.337764
포착       0.334703
팀장       0.325660
금품       0.315764
Name: 10, dtype: float64
<class 'pandas.core.series.Series'>


For topic 12 the words with the highest value are:
달러       7.110648
수지       3.549596
적자       3.326531
흑자       2.942239
경상수지     1.886183
기록       1.156509
서비스      1.082661
규모       0.859516
서비스수지    0.785960
역대       0.757219
최대       0.749589
사상       0.736844
연속       0.727599
수입       0.685084
여행       0.648828
증가       0.629518
중국인      0.626926
외국인      0.585606
내국인      0.578416
상품       0.573059
운송수지     0.543746
여행수지     0.512790
사드       0.504564
관광객      0.488400
한국은행     0.483436
Name: 11, dtype: float64
<class 'pandas.core.series.Series'>


For topic 13 the words with the highest value are:
용선료     12.051094
협상       8.548400
인하       4.046957
선주       2.745033
사채권자     1.622025
선주들      1.477358
해외       1.159649
시스팬      1.087186
채무       1.061505
집회       0.996947
타결       0.956672
조정       0.798841
선주사      0.795820
조디악      0.749435
연체       0.701533
성공       0.697897
용선       0.692240
마무리      0.668209
출자전환     0.654314
한진해운     0.626192
진행       0.612337
채권단      0.601675
다나오스     0.589096
억류       0.545780
최종       0.541714
Name: 12, dtype: float64
<class 'pandas.core.series.Series'>


For topic 14 the words with the highest value are:
인상      7.096474
운임      1.290230
금리      1.266890
feu     0.999275
아시아     0.851722
할증료     0.676417
달러      0.661358
가격      0.657014
teu     0.524214
tsa     0.506308
부과      0.505001
피트      0.495112
요금      0.494656
부담      0.471841
컨테이너    0.466333
운임인상    0.443870
증료      0.441491
성수기     0.428426
추가      0.424699
적용      0.419890
보험료     0.413870
임금      0.407170
결정      0.369106
전쟁      0.357334
해운업계    0.334095
Name: 13, dtype: float64
<class 'pandas.core.series.Series'>


For topic 15 the words with the highest value are:
수출      16.972444
미국       4.383601
자동차      4.201498
반도체      2.778488
fta      2.286208
생산       2.094346
관세       1.961954
무역       1.933985
수입       1.701209
제품       1.670759
부품       1.596091
품목       1.579030
내수       1.536879
물량       1.534828
감소       1.383450
피해       1.336275
이란       1.332565
산업       1.218292
수출액      1.181757
사태       1.143359
삼성전자     1.133867
공장       1.095280
판매       1.087298
영향       1.046940
타격       1.045518
Name: 14, dtype: float64
<class 'pandas.core.series.Series'>


For topic 16 the words with the highest value are:
경제      8.579836
성장      3.233457
금리      2.985986
위기      2.487258
정책      2.305897
한국      2.060623
미국      1.808500
기업      1.534039
가계      1.496044
투자      1.320265
상황      1.310999
일자리     1.303332
소비      1.268789
재정      1.209992
인하      1.177191
경기      1.176914
세계      1.122205
글로벌     1.017506
가계부채    1.015616
국민      0.996242
한국은행    0.979596
우리나라    0.957047
브렉시트    0.954696
사회      0.920334
성장률     0.918803
Name: 15, dtype: float64
<class 'pandas.core.series.Series'>


For topic 17 the words with the highest value are:
해양       11.548075
수산        3.381967
바다        2.973504
산업        1.751568
분야        1.581496
포럼        1.274244
해양산업      1.125297
발전        1.122770
세계        1.073318
미래        0.918101
플랜트       0.888916
항만        0.883907
수산업       0.868260
육성        0.867652
자원        0.821373
주제        0.757855
우리나라      0.728451
한국해양대     0.699430
정책        0.638448
교수        0.613143
수산물       0.607348
환경        0.552132
국가        0.547000
안전        0.538607
세션        0.521409
Name: 16, dtype: float64
<class 'pandas.core.series.Series'>


For topic 18 the words with the highest value are:

펀드        4.981477
선박펀드      3.334832
투자        1.980349
매입        1.685837
조성        1.616925
투자자       0.914614
규모        0.874061
해운업체      0.618622
자금        0.606989
선박투자회사    0.555298
선박        0.514943
운용        0.500768
건조        0.473782
수익        0.454323
시가        0.440451
방안        0.411554
출자        0.411105
배당        0.406657
공모        0.387064
출시        0.372914
회사        0.337749
민간        0.336023
사모        0.321850
인가        0.313551
구조조정기금    0.291914
Name: 17, dtype: float64
<class 'pandas.core.series.Series'>


For topic 19 the words with the highest value are:
지원          12.419265
자금           2.257532
기금           1.707331
보증           1.391445
규모           1.205220
프로그램         1.142809
확대           1.040460
해양진흥공사       1.020598
유동           1.008360
기간산업         0.994948
추가           0.957393
어려움          0.859727
대상           0.837563
중소           0.794060
고용           0.785772
공사           0.777602
중소기업         0.765592
한국해양진흥공사     0.716890
감면           0.703000
유예           0.690987
기안기금         0.642249
계획           0.635608
안정           0.625517
업종           0.624894
항공           0.590085
Name: 18, dtype: float64
<class 'pandas.core.series.Series'>


For topic 20 the words with the highest value are:
부산        16.955890
부산시        3.659868
지역         2.186184
도시         1.667564
중심지        1.482671
유치         1.306720
후보         1.071982
시민         0.940426
센터         0.823820
서병수        0.790594
공약         0.784107
설립         0.706996
bifc       0.642817
발전         0.627595
국제         0.614018
선박금융공사     0.613287
동북아        0.597689
부산항        0.595698
시장         0.589378
북항         0.581683
선거         0.555768
캠코선박운용     0.538781
허브         0.525147
육성         0.522464
개최         0.516827
Name: 19, dtype: float64
<class 'pandas.core.series.Series'>


For topic 21 the words with the highest value are:
현대그룹       15.198844
현대건설        3.293618
현대엘리베이터     3.207634
현정          2.382859
현대증권        1.883845
현대          1.561857
외환은행        1.548024
현대아산        1.418942
현대중공업       1.048626
계열사         1.024781
kcc         0.927412
현대상선        0.910301
대북사업        0.907504
현대로지스틱스     0.905364
정몽헌         0.884046
대북          0.827451
그룹          0.809527
현대차그룹       0.751614
선정          0.731023
중단          0.680576
채권단         0.678737
분쟁          0.638319
여성          0.634578
인수전         0.632292
보증금         0.631575
Name: 20, dtype: float64
<class 'pandas.core.series.Series'>


For topic 22 the words with the highest value are:
대통령       6.088287
청와대       1.096681
국민        1.079174
국회        1.057392
문재인       0.847076
박근혜       0.791579
북한        0.720547
강조        0.516853
당부        0.502053
국정        0.481933
협력        0.458431
연설        0.437304
경제        0.430061
대화        0.401996
대한민국      0.397585
방문        0.349275
총리        0.328850
이날        0.314715
극복        0.307323
개혁        0.302843
참석        0.293138
국민들       0.292972
명명식       0.284467
정치        0.282425
알헤시라스호    0.272299
Name: 21, dtype: float64
<class 'pandas.core.series.Series'>


For topic 23 the words with the highest value are:
사장        9.688749
ceo       1.836678
유창근       1.628253
참석        1.106194
회의        1.060331
선임        0.837667
이사        0.696728
김영민       0.682845
신임        0.680186
박스클럽      0.679604
이석희       0.626572
경영자       0.588181
취임        0.550019
경영        0.531195
부회장       0.528865
최고        0.524751
인천항만공사    0.519911
개최        0.494238
부사장       0.488857
박정원       0.472080
인사        0.460988
추천        0.453221
배재훈       0.438987
입사        0.426694
출신        0.417850
Name: 22, dtype: float64
<class 'pandas.core.series.Series'>


For topic 24 the words with the highest value are:
해운사     25.036794
해운사들     5.087798
머스크      3.172526
해운업      3.112558
글로벌      2.436812
중소       2.193315
조선사      2.070265
업체       2.018390
위기       1.962205
해운업계     1.847400
해운       1.826020
불황       1.545361
업계       1.467642
cma      1.411860
유동       1.337805
cgm      1.264466
세계       1.245674
중견       1.173336
관계자      1.151822
퇴출       1.123414
회사       1.104406
해운업체     1.096478
선박펀드     1.065582
침체       1.019525
경쟁       0.989683
Name: 23, dtype: float64
<class 'pandas.core.series.Series'>


For topic 25 the words with the highest value are:
매각      9.062374
지분      3.868647
자산      1.390780
유동      1.253930
확보      1.248398
보유      1.148845
자구안     0.837982
현대증권    0.833346
주식      0.794670
자회사     0.771541
사업부     0.727063
자구      0.617034
추진      0.593478
계획      0.586800
터미널     0.559524
부채      0.521114
계열사     0.514882
산업은행    0.502742
유동성     0.498213
마련      0.480321
현금      0.480002
자금      0.475155
위기      0.467276
진행      0.463601
알짜      0.453792
Name: 24, dtype: float64
<class 'pandas.core.series.Series'>


For topic 26 the words with the highest value are:
취업자      6.061988
제조업      3.568281
고용       3.118767
실업       2.656380
실업자      1.816195
실업률      1.743891
포인트      1.660325
청년       1.370403
감소       1.315425
통계청      1.300666
증가       1.136602
일자리      1.114712
청년실업률    0.971671
고용률      0.876676
상승       0.872054
지난달      0.852121
기록       0.775919
여파       0.662055
부진       0.652183
기준       0.638883
취업       0.630185
연속       0.625998
감소세      0.618635
동향       0.618015
통계       0.581316
Name: 25, dtype: float64
<class 'pandas.core.series.Series'>


For topic 27 the words with the highest value are:
stx        9.010303
stx팬오션     4.000687
stx그룹      2.569552
stx조선해양    1.303887
범양상선       1.135513
강덕수        1.100944
그룹         0.805917
stx조선      0.691427
조선         0.622956
stx중공업     0.610485
stx엔진      0.603245
에너지        0.543368
부회장        0.520311
쌍용중공업      0.495408
조선해양       0.486389
엔진         0.468269
매출         0.447946
산업은행       0.447774
stx건설      0.419388
stx에너지     0.403783
샐러리맨       0.388548
계열사        0.385887
stx유럽      0.365962
이종철        0.361699
다롄         0.323091
Name: 26, dtype: float64
<class 'pandas.core.series.Series'>


For topic 28 the words with the highest value are:
장관          6.812289
해수부         5.752968
후보자         2.791456
수산          2.171944
김영춘         1.204002
재건          1.075131
문성혁         1.074302
차관          0.744278
출신          0.738699
부처          0.723843
해양          0.708739
인사          0.673657
해양수산부       0.625420
김영석         0.615744
업무          0.610996
임명          0.602646
수산물         0.560486
한국해양진흥공사    0.540585
정책          0.527477
해양진흥공사      0.517871
계획          0.464834
어촌          0.445221
부활          0.440328
해운          0.428675
문재인         0.425768
Name: 27, dtype: float64
<class 'pandas.core.series.Series'>


For topic 29 the words with the highest value are:
노조      10.269064
파업       8.753569
임금       6.267669
노사       4.108873
사측       2.705696
투표       1.857841
육상노조     1.794734
임단협      1.771266
협상       1.738732
위원장      1.532309
중노위      1.454745
교섭       1.429726
찬반       1.429654
육상       1.377292
격려금      1.360129
쟁의       1.335462
합의       1.309299
조합원      1.300167
인상       1.234589
해상노조     1.105832
타결       1.058793
해원       1.042666
해상       1.033321
요구       1.028839
결렬       0.977935
Name: 28, dtype: float64
<class 'pandas.core.series.Series'>


For topic 30 the words with the highest value are:
회사채     4.065101
발행      2.694323
만기      1.578500
자금      0.699681
조달      0.670001
상환      0.568338
금리      0.535112
채권      0.521407
시장      0.492749
도래      0.474299
신용      0.457276
차환      0.435531
유동      0.433082
규모      0.415312
bbb     0.372312
cp      0.344339
sk해운    0.336997
차입금     0.319188
cbo     0.317155
사채      0.311521
현금      0.300676
영구      0.251981
투자자     0.246497
투자      0.242191
상황      0.223543
Name: 29, dtype: float64
<class 'pandas.core.series.Series'>


For topic 31 the words with the highest value are:
유가      3.388730
배럴      1.496678
가격      1.416778
원유      1.163668
상승      1.082460
달러      0.793433
석유      0.766232
국제유가    0.656977
하락      0.629964
항공      0.580354
국제      0.573630
고유가     0.539545
두바이유    0.492709
중동      0.470302
비용      0.428691
에너지     0.426270
유류비     0.415753
유류      0.404849
제품      0.395320
수요      0.388249
급등      0.388182
절감      0.372379
부담      0.372085
휘발유     0.368172
영향      0.367849
Name: 30, dtype: float64
<class 'pandas.core.series.Series'>


For topic 32 the words with the highest value are:
의원      6.410083
국회      1.293423
박상은     0.729476
국회의원    0.608897
시찰      0.582953
의혹      0.565203
의원들     0.531890
정치      0.501992
국감      0.463859
위원장     0.428708
결의안     0.393561
법안      0.381182
선주협회    0.378661
검찰      0.370495
발의      0.367742
위원회     0.363324
외유      0.354709
현금      0.353974
국정      0.318385
여야      0.304251
운전기사    0.289954
지적      0.286923
협회      0.266558
가방      0.262593
주장      0.262079
Name: 31, dtype: float64
<class 'pandas.core.series.Series'>


For topic 33 the words with the highest value are:
대한해운        13.993920
신청           2.371209
회생           2.240386
법원           1.844013
절차           1.703661
sm그룹         1.426594
법정관리         1.388777
삼선로직스        1.349583
개시           1.112933
이진방          0.814240
sm           0.787159
한앤컴퍼니        0.714514
용선           0.702854
벌크           0.682481
벌크선          0.679275
결정           0.664563
회생절차         0.653332
증자           0.651226
서울중앙지방법원     0.629183
기업회생절차       0.617508
서울중앙지법       0.615964
유상증자         0.557999
벌크선사         0.529578
법정           0.528466
유상           0.492901
Name: 32, dtype: float64
<class 'pandas.core.series.Series'>


For topic 34 the words with the highest value are:
공정위        3.507328
과징금        2.168173
담합         1.919670
해운법        1.744780
공동행위       1.679940
부과         1.102534
행위         1.020591
제재         0.829530
개정안        0.706183
허용         0.590072
공정거래위원회    0.561715
조사         0.500715
신고         0.492848
공정         0.491120
공정거래법      0.483898
공동         0.475747
심사보고서      0.458918
적용         0.445855
국회         0.395711
운임         0.384000
동남아        0.369860
법안         0.365814
사건         0.362515
항로         0.312523
거래법        0.302551
Name: 33, dtype: float64

<class 'pandas.core.series.Series'>


For topic 35 the words with the highest value are:
노선      6.976083
미주      3.677099
아시아     2.582167
sm상선    1.812792
유럽      1.327565
서비스     1.028624
항로      0.816329
투입      0.810655
sm      0.793234
미국      0.602580
미주노선    0.600880
서안      0.587804
운항      0.572540
개설      0.563756
북미      0.486225
sm그룹    0.477624
컨테이너    0.384267
중동      0.375247
남미      0.346014
롱비치     0.345809
베트남     0.336719
영업망     0.335794
지역      0.335650
운영      0.320716
상선      0.310409
Name: 34, dtype: float64
<class 'pandas.core.series.Series'>


For topic 36 the words with the highest value are:
규제        4.579052
imo       4.219109
연료        3.426580
배출        2.849035
가스        2.779098
온실        2.545201
스크러버      2.154970
국제해사기구    1.869947
환경        1.819993
황산화물      1.585426
감축        1.574583
배출량       1.559553
탄소        1.467488
설치        1.233871
대응        1.193151
사무총장      1.167307
사용        1.116019
저유황유      1.024733
시행        0.906514
이산화탄소     0.881224
엔진        0.878467
장착        0.839372
에너지       0.838046
설비        0.828928
암모니아      0.787832
Name: 35, dtype: float64
<class 'pandas.core.series.Series'>


For topic 37 the words with the highest value are:
캠코          10.119853
매입           1.950252
한국자산관리공사     1.345243
기금           1.110900
구조조정기금       0.909043
인수           0.764185
지원           0.761255
캠코선박운용       0.754609
금융           0.738878
선박펀드         0.735713
선박           0.676241
조성           0.652067
운용           0.636116
문창용          0.573637
공적           0.545755
자산           0.522337
구조           0.468097
역할           0.458048
프로그램         0.451493
조정           0.451239
공공           0.426930
채권           0.423944
해운사          0.414712
pf           0.403694
기관           0.379213
Name: 36, dtype: float64
<class 'pandas.core.series.Series'>


For topic 38 the words with the highest value are:
부총리       3.312478
장관        1.724529
회의        1.537275
유일호       1.347197
재정부       0.975831
경쟁력       0.956439
기획        0.927557
강화        0.867845
경제        0.815088
방안        0.746607
서울청사      0.506212
대책        0.489982
주재        0.475962
점검        0.433872
이날        0.429929
산업        0.427139
대응        0.390376
논의        0.370655
참석        0.361843
추진        0.344098
마련        0.339087
관계장관회의    0.303202
원칙        0.284416
사업재편      0.283861
현안        0.280932
Name: 37, dtype: float64
<class 'pandas.core.series.Series'>


For topic 39 the words with the highest value are:
주가       3.965172
상승       1.809206
매수       1.330292
연구원      1.200275
종목       1.080227
하락       0.962838
증시       0.907754
해운주      0.903719
외국인      0.785264
강세       0.784051
지수       0.780934
코스피      0.732268
실적       0.724965
거래       0.720492
투자       0.702959
주식       0.669621
마감       0.649192
상승세      0.622345
시장       0.598718
기대감      0.559323
증권       0.545156
애널리스트    0.543083
목표주가     0.530235
급등       0.519620
조선주      0.482774
Name: 38, dtype: float64
<class 'pandas.core.series.Series'>


For topic 40 the words with the highest value are:
중국      10.161463
한국       2.356308
일본       2.276742
세계       2.062660
시장       1.124406
미국       1.012738
상하이      0.717288
자국       0.711914
업체       0.703476
조선소      0.637589
홍콩       0.560641
cgt      0.559042
최대       0.500751
경쟁       0.491735
조선업      0.463566
현지       0.452460
유럽       0.423498
아시아      0.416886
우리나라     0.416212
점유       0.387502
철강       0.386888
수주량      0.384318
글로벌      0.380016
원자재      0.361422
대만       0.358266
Name: 39, dtype: float64
<class 'pandas.core.series.Series'>


For topic 41 the words with the highest value are:
부산항       4.409111
항만        2.283600
컨테이너      1.791351
물동량       1.623698
화물        1.519512
bpa       1.078613
환적        1.072985
신항        0.937769
처리        0.931272
터미널       0.888848
부두        0.887661
teu       0.805647
광양항       0.729621
부산항만공사    0.728721
환적화물      0.514567
물량        0.512833
인천항       0.509397
선석        0.491823
하역        0.449316
유치        0.439821
북항        0.428687
기항        0.426795
울산항       0.402940
운영사       0.383843
부산신항      0.375423
Name: 40, dtype: float64
<class 'pandas.core.series.Series'>


For topic 42 the words with the highest value are:
계약        3.780022
입찰        2.469664
운송        2.350498
수송        2.237019
장기        1.741813
유연탄       1.306500
체결        1.299806
일본        1.107912
화주        0.966441
stx팬오션    0.936276
화물        0.896052
한전        0.816588
철광석       0.761502
글로비스      0.728793
발전        0.722403
sk해운      0.659805
한국전력      0.651353
장기운송계약    0.648685
전용선       0.614406
참여        0.589199
발레        0.577499
물량        0.574744
동서발전      0.545112
컨소시엄      0.525745
업체        0.514017
Name: 41, dtype: float64
<class 'pandas.core.series.Series'>


For topic 43 the words with the highest value are:
전망     4.395703
경기     2.997115
예상     2.467132
내년     2.300721
업종     2.279334
회복     2.039371
증가     1.671415
철강     1.603069
수요     1.562936
부진     1.285177
지속     1.117107
건설     1.115746
회복세    1.080600
둔화     1.060189
자동차    1.014446
연구원    0.948614
시장     0.901694
내수     0.890879
반도체    0.822198
보고서    0.817863
성장     0.791679
물동량    0.768460
업황     0.760797
상반기    0.750757
과잉     0.716836
Name: 42, dtype: float64
<class 'pandas.core.series.Series'>


For topic 44 the words with the highest value are:
선사        6.511089
국적        1.680508
선사들       1.013755
화주        0.917687
글로벌       0.754666
선복량       0.664935
컨테이너      0.577047
원양        0.565588
파산        0.553560
국적선사      0.523061
경쟁력       0.484175
한국        0.455465
sm상선      0.450372
흥아해운      0.419909
해운업       0.415082
통합        0.412920
장금상선      0.401184
외국        0.400503
경쟁        0.372867
해운        0.359183
한국해운연합    0.310986
cgm       0.308669
cma       0.306667
확보        0.305165
항로        0.295290
Name: 43, dtype: float64
<class 'pandas.core.series.Series'>


For topic 45 the words with the highest value are:
부실        3.438624
채권        3.118583
비율        1.306103
은행        1.296852
여신        1.283144
부실채권      1.094477
부실채권비율    1.039685
포인트       0.627187
규모        0.466499
분기        0.436091
정리        0.435869
수준        0.337425
금감원       0.334908
국내은행      0.305870
은행들       0.278582
신규        0.236700
가계        0.227950
기금        0.221606
대비        0.216719
발생        0.209711
회수        0.202296
감독원       0.201199
산업은행      0.196864
조선업       0.196636
건전        0.194610
Name: 44, dtype: float64
<class 'pandas.core.series.Series'>


For topic 46 the words with the highest value are:
청문회      4.132334
증인       2.269710
여야       1.238805
채택       1.148934
수석       0.927539
원내       0.824655
합의       0.755413
최경환      0.754529
안종범      0.665725
청와대      0.640790
서별관      0.613370
홍기택      0.556529
국회       0.548196
처리       0.518620
원내대표     0.515220
출석       0.513456
규명       0.499188
부실       0.417806
조선       0.382258
회의       0.373081
더민주      0.360286
국민       0.350692
책임       0.336660
정무위      0.311753
서별관회의    0.309275
Name: 45, dtype: float64
<class 'pandas.core.series.Series'>


For topic 47 the words with the highest value are:
인수        6.257507
터미널       1.182391
sm그룹      1.071436
롱비치       0.912258
지분        0.892015
인수전       0.782846
합병        0.716933
한앤컴퍼니     0.672439
범양상선      0.624604
컨소시엄      0.576332
대한통운      0.530775
참여        0.515313
msc       0.514844
자산        0.513899
pef       0.508834
입찰        0.483547
롱비치터미널    0.474035
우선        0.409873
선정        0.404702
현대건설      0.399268
본계약       0.375460
협상        0.368420
사모펀드      0.359021
본입찰       0.356120
시너지       0.348381
Name: 46, dtype: float64
<class 'pandas.core.series.Series'>


For topic 48 the words with the highest value are:
추경      5.285539
예산      1.929025
국회      1.431096
처리      1.344061
여야      1.249965
편성      1.222159
추경안     1.194939
일자리     0.694409
통과      0.655646
본회의     0.628737
누리      0.626072
예산안     0.575473
원내      0.562249
합의      0.522770
집행      0.493271
심사      0.486534
의장      0.470604
민생      0.468431
정책위     0.438093
경정      0.401664
누리과정    0.381604
무산      0.378198
국민      0.367713
더민주     0.345687
예결위     0.345309
Name: 47, dtype: float64
<class 'pandas.core.series.Series'>


For topic 49 the words with the highest value are:
컨테이너선    5.229221
teu      4.584433
발주       2.711463
컨테이너     2.306337
세계       1.586726
선복량      1.517861
인도       1.170994
머스크      0.991885
최대       0.733650
물동량      0.715136
규모       0.639688
투입       0.618404
피트       0.576621
계획       0.516276
해운       0.469975
초대형      0.461499
선대       0.460031
msc      0.417778
명명식      0.407111
내년       0.400936
유럽       0.393398
글로벌      0.371618
시장       0.359057
크기       0.350343
아시아      0.349079
Name: 48, dtype: float64
<class 'pandas.core.series.Series'>


For topic 50 the words with the highest value are:
bdi       4.584477
벌크선       3.117006
철광석       2.129285
지수        1.797053
시황        1.405499
포인트       1.143694
석탄        0.983282
기록        0.865852
하락        0.714459
곡물        0.697918
원자재       0.694278
상승        0.672150
벌크        0.650908
상승세       0.643034
운임        0.595086
발틱운임지수    0.585625
수요        0.566643
bdi지수     0.537143
회복        0.534811
케이프       0.499720
경기        0.493283
하락세       0.486654
유조선       0.470326
건화물선      0.467700
중국        0.464100
Name: 49, dtype: float64
<class 'pandas.core.series.Series'>


For topic 51 the words with the highest value are:
채권단      5.446008
협약       1.496898
자율       1.492273
자율협약     1.365122
신청       1.275892
법정관리     1.148586
자구안      0.867581
산업은행     0.809772
결정       0.695134
자금       0.690038
정상       0.644886
자구       0.624893
관리       0.605214
추가       0.592232
채무       0.580446
한진그룹     0.559172
법정       0.530323
제출       0.523942
지원       0.430403
조건부      0.405810
경영정상화    0.398054
경영       0.394018
방안       0.390507
부족       0.385332
회생       0.377194
Name: 50, dtype: float64
<class 'pandas.core.series.Series'>


For topic 52 the words with the highest value are:

대출      4.428901
은행      1.853083
연체      1.346059
중소기업    1.091195
가계      0.872890
연체율     0.784670
금리      0.680932
은행들     0.607664
담보      0.541123
여신      0.435524
부동산     0.424772
자금      0.412340
포인트     0.411064
시중      0.367366
가계대출    0.354985
잔액      0.328213
주택      0.322832
금융      0.303991
은행권     0.299138
관리      0.272840
예금      0.271711
리스크     0.263800
우리은행    0.241784
심사      0.237943
시중은행    0.233908
Name: 51, dtype: float64
<class 'pandas.core.series.Series'>


For topic 53 the words with the highest value are:
해운동맹      3.141126
얼라이언스     2.180381
가입        2.180022
동맹        1.886835
머스크       0.733687
세계        0.670867
결성        0.631167
msc       0.521629
오션        0.477493
협력        0.451307
재편        0.449893
합류        0.405989
하팍로이드     0.397378
회원사       0.390180
ckyhe     0.353548
디얼라이언스    0.323136
현대상선      0.301575
글로벌       0.292979
cma       0.286172
cgm       0.282171
소속        0.275076
출범        0.274419
선복        0.270286
내년        0.264627
항로        0.264066
Name: 52, dtype: float64
<class 'pandas.core.series.Series'>


For topic 54 the words with the highest value are:
대우조선      3.998849
대우조선해양    3.682251
산업은행      1.066563
산은        0.641360
vlcc      0.623532
현대중공업     0.599594
삼성중공업     0.545922
조선        0.499506
회사        0.399580
남아공       0.385756
손실        0.384579
부실        0.379629
스마트십      0.376467
책임        0.352266
회계        0.344070
분식        0.312244
국책은행      0.299502
옥포조선소     0.279348
건조        0.278546
경영        0.268936
이동걸       0.260696
혈세        0.259843
남상태       0.257514
초대형       0.255668
경영진       0.249572
Name: 53, dtype: float64
<class 'pandas.core.series.Series'>


For topic 55 the words with the highest value are:
lng       4.688867
천연가스      0.633758
연료        0.528198
추진선       0.527175
운반선       0.525199
벙커링       0.520178
카타르       0.514225
액화        0.483042
가스공사      0.444005
lng선      0.379917
한국가스공사    0.323398
건조        0.269267
추진        0.255749
발주        0.233647
수요        0.218222
세계        0.192942
한국        0.185892
삼성중공업     0.181357
가스        0.179760
fsru      0.170070
에너지       0.150186
화물창       0.139696
사용        0.138355
지분        0.126518
수송        0.124226
Name: 54, dtype: float64
<class 'pandas.core.series.Series'>


For topic 56 the words with the highest value are:
전년       2.981688
증가       2.649219
대비       2.481041
동기       1.724679
감소       1.591750
순이익      1.123761
기록       0.805205
물동량      0.557550
분기       0.532986
상반기      0.470968
포인트      0.446223
매출액      0.444165
당기순이익    0.436293
순익       0.402469
기간       0.385665
당기       0.373478
상승       0.367326
하락       0.323488
이자이익     0.290647
집계       0.280421
대손비용     0.244041
개선       0.239963
영향       0.234137
대손       0.228214
지표       0.223408
Name: 55, dtype: float64
<class 'pandas.core.series.Series'>


For topic 57 the words with the highest value are:
그리스      3.959139
유로존      0.447075
유럽       0.402641
아테네      0.356868
유로       0.310697
국가       0.263509
eu       0.250959
재정       0.240624
총리       0.235208
디폴트      0.233491
복지       0.219926
연금       0.219388
위기       0.209799
세계       0.188873
gdp      0.181525
선주       0.165419
나라       0.152886
구제       0.150445
한국       0.144230
파판드레우    0.137535
세금       0.134299
imf      0.127982
구제금융     0.124689
유로화      0.121976
사태       0.121361
Name: 56, dtype: float64
<class 'pandas.core.series.Series'>


For topic 58 the words with the highest value are:
여객선      1.945212
제주       1.790782
항로       1.545837
인천       1.378455
운항       1.210759
여객       0.807808
인천항      0.689896
연안       0.639210
취항       0.541819
청해진해운    0.539494
카페리      0.467396
크루즈      0.434307
면허       0.406951
대저건설     0.371203
뱃길       0.367650
사업자      0.338183
이용객      0.315750
개설       0.306042
대산항      0.304095
선령       0.297646
세월호      0.285884
화물       0.282374
중단       0.273948
관광객      0.238598
승객       0.221219
Name: 57, dtype: float64
<class 'pandas.core.series.Series'>


For topic 59 the words with the highest value are:
한진그룹       2.902571
대한항공       2.727728
조양호        1.082950
한진해운       0.674817
자금         0.609311
한진         0.602241
담보         0.541251
이사회        0.388206
아시아나항공     0.360626
한진칼        0.354562
항공         0.313992
항공사        0.295144
지분         0.291461
조중훈        0.284059
하역         0.280779
사재         0.272447
한진해운홀딩스    0.269739
경영         0.266657
지원         0.257807
대주주        0.250557
책임         0.244532
화물         0.221224
자구안        0.216711
주주         0.215410
부채비율       0.213079
Name: 58, dtype: float64
<class 'pandas.core.series.Series'>


For topic 60 the words with the highest value are:
충당금       2.251535
농협은행      1.815667
농협금융      1.206808
여신        1.155966
상반기       1.058410
농협        0.923952
은행        0.869707
순이익       0.812096
적립        0.803378
조선        0.709588
손실        0.487140
당기        0.455867
농협금융지주    0.452535
nh        0.430728
농협중앙회     0.425355
적자        0.390821
익스포저      0.370817
대손        0.369038
김용환       0.352197
빅배스       0.339295
우리은행      0.331452
순익        0.307781
금융        0.295549
부담        0.286454
당기순이익     0.283300
Name: 59, dtype: float64
<class 'pandas.core.series.Series'>


For topic 61 the words with the highest value are:
포스코        3.781825
진출         0.991757
대우로지스틱스    0.720498
설립         0.717968
자회사        0.588760
철강         0.413357
물류자회사      0.378136
해운업        0.376412
통합         0.367923
대우인터내셔널    0.270472
철회         0.263845
해운업계       0.258221
반발         0.251732
대량화주       0.248650
제품         0.216598
원료         0.216440
화주         0.213393
법인         0.187913
선주협회       0.176337
업계         0.174207
관계자        0.169727
포스코gsp     0.168688
대량         0.165273
반대         0.159901
해총         0.149429
Name: 60, dtype: float64
<class 'pandas.core.series.Series'>


For topic 62 the words with the highest value are:
해적        2.624387
소말리아      1.420645
피랍        0.651040
해적들       0.610094
납치        0.495812
해역        0.450993
아덴만       0.373993
공격        0.363203
퇴치        0.303369
사건        0.284773
보안        0.269837
삼호주얼리호    0.260727
청해부대      0.242779
인도양       0.241749
선원        0.239666
삼호해운      0.232051
발생        0.220274
요원        0.206906
해군        0.195925
피해        0.192411
삼호드림호     0.190283
cgpcs     0.185350
몸값        0.184334
국토부       0.169958
해적사건      0.165657
Name: 61, dtype: float64
<class 'pandas.core.series.Series'>


For topic 63 the words with the highest value are:
약정          3.092909
재무          2.434457
체결          1.624881
개선          1.506026
외환은행        1.223505
구조          0.892029
대상          0.655885
현대그룹        0.638140
은행          0.460504
평가          0.415236
금융권         0.380605
채권단         0.377590
부채비율        0.369459
재무약정        0.323283
주채권은행       0.323130
부채          0.306430
변경          0.297954
특성          0.264834
이해          0.263766
거래은행        0.251216
선정          0.251090
mou         0.236291
재무구조        0.225495
제외          0.215529
재무구조개선약정    0.213103
Name: 62, dtype: float64
<class 'pandas.core.series.Series'>


For topic 64 the words with the highest value are:
한은        1.805780
자본        1.628657
수은        1.328328
산은        1.284095
확충        1.114699
은행        1.018756
국책        0.875207
출자        0.872566
국책은행      0.851271
한국은행      0.655514
산업은행      0.622704
수출입은행     0.611272
bis       0.525254
발권력       0.451665
완화        0.422412
코코본드      0.421204
총재        0.394635
자본확충펀드    0.383906
자본확충      0.363832
발행        0.347381
비율        0.338082
중앙은행      0.325943
동원        0.311215
방식        0.268929
재정        0.257788
Name: 63, dtype: float64
<class 'pandas.core.series.Series'>


For topic 65 the words with the highest value are:
팬오션       5.045561
하림그룹      0.973304
곡물        0.952353
하림        0.908377
stx팬오션    0.671081
법정관리      0.454095
벌크        0.303684
김홍국       0.299147
인수        0.288356
법정        0.286540
벌크선       0.265437
카길        0.244176
관리        0.244136
벌크선사      0.232051
회생        0.216596
사료        0.208557
추성엽       0.197699
절차        0.190403
현대글로비스    0.187446
신청        0.178487
발레        0.165365
계약        0.158415
법원        0.151652
닭고기       0.145603
매각        0.143518
Name: 64, dtype: float64
<class 'pandas.core.series.Series'>


For topic 66 the words with the highest value are:
운하       2.281898
수에즈      1.215722
파나마      0.897376
이집트      0.479692
개통       0.420604
희망봉      0.401131
확장       0.378317
우회       0.342783
파나마운하    0.306645
통과       0.287570
수에즈운하    0.266481
좌초       0.260812
에버기븐호    0.223527
항로       0.199346
사고       0.185653
통항       0.169860
유럽       0.168641
통행료      0.166712
통행       0.165367
사태       0.160969
아시아      0.159813
컨테이너선    0.148247
대기       0.136512
선박       0.131516
에버       0.127948
Name: 65, dtype: float64
<class 'pandas.core.series.Series'>


For topic 67 the words with the highest value are:
해운        3.061221
산업        1.701705
해운산업      0.842619
조선        0.587598
재건        0.560595
세계        0.550923
협회        0.535885
한국        0.469262
발전        0.459242
경쟁력       0.451027
한국선주협회    0.420368
우리나라      0.408089
위기        0.359331
개최        0.349975
세미나       0.332625
선주        0.311333
협력        0.303612
극복        0.290708
참석        0.285338
국가        0.272817
선주협회      0.267139
상생        0.250713
정책        0.246224
조선산업      0.235304
강국        0.224031
Name: 66, dtype: float64
<class 'pandas.core.series.Series'>


For topic 68 the words with the highest value are:
국세청       1.581967
세금        1.206172
탈세        1.124936
추징        0.833155
법인        0.753772
시도상선      0.683767
조세        0.678516
조세피난처     0.664066
역외        0.595974
법인세       0.517323
조사        0.517163
혐의        0.458554
홍콩        0.454697
권혁        0.449473
과세        0.430217
소득        0.402059
위장        0.381804
해외        0.372845
피난처       0.339504
spc       0.310462
페이퍼컴퍼니    0.309673
탈루        0.303254
회사        0.290594
세무조사      0.283177
설립        0.265835
Name: 67, dtype: float64
<class 'pandas.core.series.Series'>


For topic 69 the words with the highest value are:
사업     2.852453
강화     1.090444
추진     0.969426
계획     0.944699
서비스    0.850306
구축     0.742850
확대     0.727997
경쟁력    0.727163
투자     0.684697
확보     0.614482
분야     0.582959
전략     0.564118
진출     0.507069
운영     0.442301
시장     0.432066
경영     0.427845
혁신     0.421135
글로벌    0.393987
창출     0.386686
해외     0.386210
관리     0.378279
미래     0.371879
성장     0.349251
역량     0.341895
방침     0.339225
Name: 68, dtype: float64

<class 'pandas.core.series.Series'>


For topic 70 the words with the highest value are:
금강산          1.970838
관광           1.719898
사업           0.627704
테마           0.605073
북한           0.525831
크루즈          0.495747
영위           0.386683
남북           0.365772
아난티          0.365529
현대아산         0.357452
재개           0.312343
일신석재         0.254001
평화크루즈        0.246992
리조트          0.227127
제재           0.225209
팬스타엔터프라이즈    0.212684
제조사          0.207820
지구           0.182625
대가           0.181532
관광객          0.174626
대북           0.173493
보유           0.156133
북측           0.149509
현대엘리베이       0.148592
운영           0.146185
Name: 69, dtype: float64
<class 'pandas.core.series.Series'>


For topic 71 the words with the highest value are:
지역      2.204819
울산      1.562382
경남      1.090461
조선      0.936268
전국      0.771472
조선업     0.482537
업체      0.449059
기자재     0.386955
생산      0.361035
거제      0.341757
경기      0.284264
아파트     0.280288
인구      0.268694
소비      0.260662
서울      0.257806
부산은행    0.249725
부동산     0.237193
산업      0.235610
조선소     0.234561
지방      0.230133
통계청     0.226970
경제      0.223843
주택      0.221013
서비스업    0.219448
동남      0.215477
Name: 70, dtype: float64
<class 'pandas.core.series.Series'>


For topic 72 the words with the highest value are:
금융          3.573611
설립          1.507919
기관          1.050138
선박금융공사      0.798046
선박금융        0.764090
공사          0.615335
위원장         0.579713
보증          0.558721
금융위         0.492394
업무          0.382647
자본금         0.341754
수출입은행       0.325669
부산은행        0.322865
해운보증기금      0.312216
중심지         0.299265
한국해양보증보험    0.299069
산업은행        0.283804
정책금융공사      0.281254
센터          0.278556
해양금융종합센터    0.272763
전문          0.267271
정책          0.266206
정책금융기관      0.254950
역할          0.241062
해운보증기구      0.235072
Name: 71, dtype: float64
<class 'pandas.core.series.Series'>


For topic 73 the words with the highest value are:
대표      2.526744
이사      0.786358
국회      0.430658
원내      0.406636
선임      0.368818
신임      0.357405
원내대표    0.309895
의장      0.305671
대표이사    0.288348
김종인     0.282139
연설      0.276496
내정자     0.224427
국민      0.218973
민생      0.216981
더민주     0.211612
부사장     0.206351
부회장     0.194899
정책위     0.183100
정진석     0.180986
대책      0.180674
비상      0.179807
이날      0.159845
간담회     0.151279
정치      0.148250
추미애     0.147512
Name: 72, dtype: float64
<class 'pandas.core.series.Series'>


For topic 74 the words with the highest value are:
선원       2.127992
채용       0.717197
인력       0.588985
승선       0.562546
해기사      0.560519
교육       0.477686
선장       0.463451
양성       0.462001
선원들      0.430070
일자리      0.356649
외국인      0.331372
취업       0.326591
여성       0.322516
직원       0.305427
고용       0.296575
근무       0.294703
한국해양대    0.262690
대학       0.251906
임금       0.246777
항해사      0.236463
제도       0.233283
신입       0.188628
예비역      0.168521
인원       0.156419
기관장      0.147417
Name: 73, dtype: float64
<class 'pandas.core.series.Series'>


For topic 75 the words with the highest value are:
북극항로      1.833188
현대글로비스    1.193222
북극        0.708626
북극해       0.607587
러시아       0.538456
항로        0.521652
운항        0.511853
이용        0.289821
쇄빙선       0.283884
시범        0.271299
얼음        0.248176
유럽        0.205440
울산항       0.187198
개척        0.184867
글로비스      0.172629
노르웨이      0.142757
단축        0.139154
시범운항      0.137761
거리        0.121194
자원        0.114530
항해        0.109060
수에즈운하     0.101640
세미나       0.101158
쇄빙        0.100250
해빙        0.096991
Name: 74, dtype: float64
<class 'pandas.core.series.Series'>


For topic 76 the words with the highest value are:
환율      2.249035
달러      0.664796
하락      0.654021
원화      0.606837
외화      0.376668
부채      0.274405
달러화     0.256185
영향      0.214042
강세      0.212423
약세      0.208934
환차손     0.208716
상승      0.191496
외화부채    0.186188
변동      0.185151
엔화      0.184621
환율하락    0.182780
결제      0.182144
환산      0.172115
회계      0.152491
환차익     0.143003
비중      0.140319
통화      0.136372
기업들     0.132803
악화      0.132125
삼성전자    0.131666
Name: 75, dtype: float64
<class 'pandas.core.series.Series'>


For topic 77 the words with the highest value are:
기업        2.247808
평가        1.115719
신용        0.904152
대상        0.822708
워크아웃      0.671491
위험        0.572628
기업들       0.338182
퇴출        0.336814
건설        0.333877
중소기업      0.321850
업체        0.320587
업종        0.305951
건설사       0.276760
결과        0.267018
대기업       0.264295
선정        0.251013
은행들       0.241558
분류        0.240029
신용위험평가    0.225414
공여액       0.203469
금감원       0.195256
채권은행들     0.180444
옥석        0.171433
절차        0.151861
조정        0.146360
Name: 76, dtype: float64
<class 'pandas.core.series.Series'>


For topic 78 the words with the highest value are:
물류        2.401721
운송        0.369727
화물        0.325469
글로비스      0.253665
물류산업      0.220858
대한통운      0.216262
화주        0.214564
현대글로비스    0.201077
물류업       0.188090
항만        0.179752
해상        0.157088
대란        0.153692
물류기업      0.143316
수출입       0.138725
성장        0.136028
동북아       0.134982
기업        0.134686
서비스       0.130583
자회사       0.128786
하역        0.121958
물량        0.112716
물류업계      0.102492
육상        0.098144
택배        0.095455
국가        0.092441
Name: 77, dtype: float64
<class 'pandas.core.series.Series'>


For topic 79 the words with the highest value are:
실적        2.076863
영업        1.566696
이익        1.381707
매출        1.295816
영업이익      1.268818
흑자        0.854031
기록        0.782357
매출액       0.637954
손실        0.618007
적자        0.616328
분기        0.541682
개선        0.503383
전환        0.423319
흑자전환      0.411904
달성        0.391863
영업손실      0.376541
순이익       0.305781
사상        0.294435
최대        0.288927
stx팬오션    0.268416
당기        0.268033
상반기       0.262410
수익        0.252542
예상        0.226420
기간        0.202611
Name: 78, dtype: float64
<class 'pandas.core.series.Series'>


For topic 80 the words with the highest value are:
사고       1.727518
안전       1.252300
선장       0.800795
해경       0.699767
참사       0.682322
침몰       0.636964
세월호      0.614240
국민       0.538054
청해진해운    0.463167
재난       0.341802
관리       0.335910
책임       0.332726
감독       0.312144
원인       0.310788
여객선      0.309885
발생       0.290576
업무       0.282747
해운조합     0.264024
해수부      0.253518
사회       0.252618
점검       0.235587
항해사      0.230925
대한민국     0.219727
출항       0.214668
구조       0.211688
Name: 79, dtype: float64
<class 'pandas.core.series.Series'>

In [12]:
result=pd.DataFrame()
for topic in range(components_df.shape[0]):
    tmp = components_df.iloc[topic]
    tt=tmp.nlargest(20)
    tmp_df=pd.DataFrame(tt)
    result=result.append(tmp_df)

In [13]:
result=result.transpose()
result.to_excel('tmp.xlsx')

In [14]:
df=get_topics(model,80).transpose()
df.to_excel('Result.xlsx')
print("Result Out")

Result Out